### PR TITLE
[invoice] manage invoicing/display in case of deleted service

### PR DESCRIPTION
**Pull request by osallou**
if a service is deleted but orders/projects still refer to this service, show it anyway in related edition, and fix invoicing to show/use this service

### CODE REVIEW

**Comment by osallou** [comment]
@gaetanHerve boulot fait à priori pour la partie service, mm "principe" pour les bookings,  mais sans doute plus d'impact (packages, supplementaries, quantities)

**Comment by osallou** [comment]
@gaetanHerve on merge celle ci?

**Comment by gaetanHerve** [comment]
je ne l'ai pas testée encore. Je jette un oeil demain matin

**Review by gaetanHerve — APPROVED** [review]
tested and approved :)

**Pull request merged**
