### PR TITLE
fix for #709 issue 2 on status list, issue 5 on alignment and speedup…

### PR DESCRIPTION
**Pull request by osallou**
… on requests

### CODE REVIEW

**Comment by osallou** [comment]
@gaetanHerve I did a few fixes for  #709 but not all

* did not check photo issue
* sql still could be improved....
* search on espece
* csv export (indeed exports all)

**Comment by osallou** [comment]
@gaetanHerve on merge?

**Comment by gaetanHerve** [comment]
Non, il manque encore des éléments

**Comment by gaetanHerve** [comment]
ok pour moi

**Pull request merged**
