### PR TITLE
Feature quote template

### PR DESCRIPTION
**Pull request by osallou**
Manage quote template on its own rather than use invoice template (in module config like for invoices)

Migration copies existing invoice template to quote for backward compat

If no template defined, show a warning in config, but at runtime use default templates (externals/pfm/templates/[invoice|quote]_template.twig

Add *company* info to template rendering

Update templates to use only company/clientinfo etc... (more generic)

### CODE REVIEW

**Comment by osallou** [comment]
I have an issue wirh pdf, certainly after sync with develop.
Pdf created but can t open it.
Working on this

**Comment by osallou** [comment]
> I have an issue wirh pdf, certainly after sync with develop. Pdf created but can t open it. Working on this

Fixed!

**Comment by osallou** [comment]
@gaetanHerve ?

**Comment by gaetanHerve** [comment]
I forgot that. I'm taking a look

**Review by gaetanHerve — APPROVED** [review]
Ok to me. I just saw that images from another space (for example "data/invoices/8/LogoH2P2.jpg" in space 41) can be used in both invoices and  quotes templates. If I remember well, trying to do that was generating an error before... (not linked to this PR, also the case on develop branch)

**Comment by osallou** [comment]
File access cannot be limited in templates (images)

**Pull request merged**
