### PR TITLE
add rgpc/privacy page

### PR DESCRIPTION
**Pull request by osallou**
relates to #364

### CODE REVIEW

**Comment by osallou** [comment]
Screenshot from 2021-12-07 11-16-57

**Comment by osallou** [comment]
Text at https://github.com/bgo-bioimagerie/platformmanager/pull/435/files#diff-21094ec8da5b486d376f775619a31c6803af336613b6cc020c34caf4483a3008

**Comment by OlivierCollin** [comment]
Seems nice to me.

**Comment by OlivierCollin** [comment]
It seems nice to me (but I am not by no means a GDPR expert)
A few remarks :
- concerning the Logs, since the GDPR wants that only data required are collected, the phrasing "other statistics" may need some clarification because it gives the impression that there are some other data collected. 
- should we mention some DPO that can be contacted by users ? It could be the Univ Rennes 1 DPO ? 
- the data deletion case is covered but what about data access and modification ?

**Comment by osallou** [comment]
dpo is pfm "admin" contact , not related to univ rennes 1....  if someone contacts univ to be removed from pfm....

for data access and modification he has direct access in his settings but I can add it

**Comment by osallou** [comment]
for logs, I keep it "general", but this basically apache logs,

**Comment by osallou** [comment]
merged but text will still not to be improved

**Pull request merged**
