### PR TITLE
use bcrypt algo for passwords

### PR DESCRIPTION
**Pull request by osallou**
keep compat with existing ones, setting… algo new core_users column to md5

add passwordEncode and comparePasswords methods in core_users, with hash parameter.
Default is to use bcrypt for new/modifications.

use jquery npm instead of copied unversioned lib

### CODE REVIEW

**Comment by osallou** [comment]
also remove old libs not used anymore

**Comment by osallou** [comment]
to be tested with prod backup

**Review by gaetanHerve — COMMENTED** [review]
why all that bootstrap deletions ?

**Comment by osallou** [comment]
for bootstrap, not related, but use npm installed library  instead of copied local version

**Review by gaetanHerve — APPROVED** [review]
tried to connect with an existing user, then created one and been able to connect PFM. Seems ok to me

**Pull request merged**
